/**
 * Expo config plugin: keep ML Kit barcode scanning out of RELEASE builds.
 *
 * expo-dev-launcher declares these as `implementation`, not `debugImplementation`,
 * so they compile into every variant:
 *
 *   com.google.android.gms:play-services-code-scanner:16.1.0
 *   com.google.mlkit:barcode-scanning:17.3.0
 *
 * The app has no barcode or QR feature. Shipping them costs several MB of
 * download, and registers com.sassagold.whereami.mlkitinitprovider — a
 * ContentProvider under our own package that initialises at every launch — plus
 * GmsBarcodeScanningDelegateActivity and the Firebase BarcodeRegistrar /
 * VisionCommonRegistrar. That is a second Firebase-linked surface in an app that
 * declares no analytics.
 *
 * ── Why this is release-only, and must stay that way ────────────────────────
 * A blanket `configurations.all { exclude ... }` also strips it from DEBUG, and
 * expo-dev-launcher uses that scanner to read the Metro QR code. Removing it
 * there breaks the development workflow rather than the shipped app. Matching on
 * configuration name keeps debug intact.
 *
 * Android names its per-variant configurations after the variant, so every
 * release configuration — releaseCompileClasspath, releaseRuntimeClasspath,
 * releaseImplementation and friends — starts with "release". Debug ones do not.
 *
 * ── Why this is edited via a plugin rather than in android/ ─────────────────
 * android/ is gitignored (.gitignore:45) because it is generated by prebuild.
 * An edit there would survive locally and vanish from every EAS build.
 *
 * ── Related ────────────────────────────────────────────────────────────────
 * This replaces plugins/withMlkitOrientationFix.js, which existed only to strip
 * android:screenOrientation from GmsBarcodeScanningDelegateActivity so Play would
 * stop flagging an orientation restriction. With the library gone from the Play
 * artifact the advisory has no source — and keeping that plugin would be worse
 * than useless: it writes the activity into the app's own AndroidManifest.xml,
 * which is variant-agnostic, so with nothing contributing the activity in release
 * the node would survive the merge and ship a declaration pointing at a class
 * that is not in the APK.
 *
 * ── Verify before shipping ──────────────────────────────────────────────────
 * This is a gradle-level change to release builds — the same category that broke
 * location in 1.3.0 and 1.4.0. Build the EAS `preview` profile (release build,
 * installable APK), install on a real phone, and check startup, notifications
 * and location. A debug build cannot prove anything here, because the exclude
 * deliberately does not apply to it.
 */
const { withAppBuildGradle } = require("@expo/config-plugins");

const MARKER = "// MLKit barcode scanning: release-only exclude";

module.exports = function withMlkitReleaseExclude(config) {
  return withAppBuildGradle(config, (mod) => {
    if (mod.modResults.language !== "groovy") {
      throw new Error(
        `withMlkitReleaseExclude expects a groovy build.gradle, got ${mod.modResults.language}`
      );
    }

    // Idempotent: prebuild can run repeatedly against the same file.
    if (mod.modResults.contents.includes(MARKER)) {
      return mod;
    }

    const block =
      `\n${MARKER}\n` +
      "// expo-dev-launcher declares these as `implementation`, so they reach every\n" +
      "// variant. The app has no barcode feature. Debug keeps them deliberately —\n" +
      "// expo-dev-launcher scans the Metro QR code with them.\n" +
      "configurations.matching { it.name.startsWith('release') }.all {\n" +
      "    exclude group: 'com.google.android.gms', module: 'play-services-code-scanner'\n" +
      "    exclude group: 'com.google.mlkit', module: 'barcode-scanning'\n" +
      "}\n";

    mod.modResults.contents += block;
    return mod;
  });
};
